### PR TITLE
Update instuctions for using travis

### PR DESCRIPTION
**Pull request by bjgill**
It seems as if the old jq command wasn't quite working. Also need to add the '-L' curl flag to get it to follow redirects.

### CODE REVIEW

**Comment by danielpsf** [comment]
This works for me. 😉 

The command from the current README.md: https://travis-ci.org/danielpsf/fields-statistics/builds/541862012

The new command (from this PR): https://travis-ci.org/danielpsf/fields-statistics/builds/541864655

**Comment by danielpsf** [comment]
Well, it fails from time to time, but I don't know if this is related to the command or the Codacy infrastructure to download the content. 😢 

https://travis-ci.org/danielpsf/fields-statistics/builds/542228691

**Comment by bjgill** [comment]
Ah - I wonder if you've hit the same thing I did. I was finding that the github requests were failing due to rate limiting. I changed the github API requests to use a Personal Access Token, and stopped seeing failures.

See https://github.com/alphagov/verify-saml-libs/commit/7090a5ef982fe8e5c44edb08f7ed2b8d88ccd125 for an example of me doing this.

**Comment by ljmf00** [comment]
Closed due to PR #131 .

**Pull request closed without merging**
