### PR TITLE
WIP test: Add test for get.sh script + alpine environments

### PR DESCRIPTION
**Pull request by franciscodua**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/repositories/CoverageServiceRepository.scala  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5193815&bid=17035169)

**Comment by josemiguelmelo** [comment]
Superseded by #182

**Pull request closed without merging**
