### PR TITLE
updated troubleshooting steps

### PR DESCRIPTION
**Pull request by amitmawkin**
based on discussion with Codacy support ,Thanks to Rafael from Codacy for helping

### CODE REVIEW

**Comment by pedrorijo91** [comment]
:+1: thanks !

Nevertheless, I would rather not to use the \<code> tags and use markdown typical syntax with \``` 
And I think this information would make more sense in a section 'Usage', indicating the full path should be specified, as long with information about available flags.

Will wait for @machadoit feedback

**Comment by machadoit** [comment]
Yeah looks great, thanks! Like @pedrorijo91 said, can you use \``` instead of the \<code\> tag?
The 'Usage' is our 'Updating Codacy', we will review this documentation if it's not clear, but for now let the info in the Troubleshooting as you did. :+1:

**Comment by amitmawkin** [comment]
Done the changes, please review

**Comment by machadoit** [comment]
Still missing the last line ;)

**Comment by amitmawkin** [comment]
something weird let me submit another one

**Pull request closed without merging**
