### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aharonha**
Getting the latest version from public repository (rather then GitHub releases)

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@aharonha thanks for your contribution.

Overall looks good but I would prefer if we did not remove the previous option.
Can you add an extra option after the other with your suggestion?

**Comment by rtfpessoa** [comment]
@aharonha did you see my comment?

**Comment by rtfpessoa** [comment]
Closing this for now due to inactivity. In the meanwhile if you see my comment we can re-open this.

**Comment by aharonha** [comment]
Actually the first time I made the pull request , the script worked.
After the latest release, my build was starting to fail.
The root cause is the change in deployment you made, making the latest
version available on Maven central repository. On the other hand, in
GitHub, which the original script was depending on, started to fail. I
believe it has to do with the fact that no jars was uploaded to GitHub
since 3.0

So, if the latest version is both available on central and it's fixing an
issue that the latest version available on GitHub meets, the latest version
should be downloaded from Central only.

(making the old script useless)


בתאריך יום ב׳, 26 במרץ 2018, 17:34, מאת Rodrigo Fernandes ‏<
notifications@github.com>:

**Pull request closed without merging**
