### PR TITLE
feat: Add Heroku CI support

### PR DESCRIPTION
**Pull request by jeremiemv**
Adding support for Heroku CI
https://devcenter.heroku.com/articles/heroku-ci

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/rules/commituuid/providers/HerokuCIProvider0.scala  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5373078&bid=17613296)

**Comment by rtfpessoa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/rules/commituuid/providers/HerokuCIProvider.scala  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=5373078&bid=17613296)

**Comment by lolgab** [comment]
Hi @jeremiemv,
Would you mind rebasing on top of master?
We made a change to allow PRs from forks

**Comment by lolgab** [comment]
Thank you for your contribution!

**Comment by jeremiemv** [comment]
You're welcome 😊

**Pull request merged**
