### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stefanvacareanu7**

### CODE REVIEW

**Comment by stefanvacareanu7** [comment]
@prcr The ' from "isn't" together with ```bash is causing that after that ' to have no colors for the closing brackets. This is a very minor change, so we can ignore it if it doesn't make sense

**Comment by lolgab** [comment]
As an alternative you can remove the bash syntax highlighting

**Comment by stefanvacareanu7** [comment]
Sounds good to me as well. Let's do it

**Review by prcr — APPROVED** [review]
:shipit:

**Pull request merged**
